apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 1
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      containers:
        - name: webserver
          image: localhost:32000/apiserver
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              hostPort: 8080
