apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
spec:
  selector:
    matchLabels:
      app: apiserver
  replicas: 1
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: apiserver
    spec:
      containers:
      - name: webserver
        image: localhost:32000/apiserver
        imagePullPolicy: Always
        env:
        - name: FLASK_APP
          value: "app.py"
        ports:
        - containerPort: 8080
          hostPort: 8080
        - containerPort: 5000
          hostPort: 5000
