apiVersion: apps/v1
kind: Deployment
metadata:
  name: faceswap
spec:
  selector:
    matchLabels:
      app: faceswap
  replicas: 1
  template:
    metadata:
      labels:
        app: faceswap
    spec:
      containers:
        - name: webserver
          image: localhost:32000/faceswap
          imagePullPolicy: Always
