apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
spec:
  selector:
    matchLabels:
      run: load-balancer-example
  replicas: 1
  template:
    metadata:
      labels:
        run: load-balancer-example
    spec:
      containers:
        - name: nats
          image: nats:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 4222
            hostPort: 4222
          - containerPort: 8222
            hostPort: 8222
          - containerPort: 6222
            hostPort: 6222
