apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  selector:
    matchLabels:
      app: neo4j
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 7687
            hostPort: 7687
          - containerPort: 7474
            hostPort: 7474
